### ISSUE TITLE
Be prepared for strange compression formats

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#85]
I known the error is not from latest release, but the issue is valid for the latest also. I have done something (fixed the running executors) but I have not to time to finalize it for commit now.

2015-11-14 20:49:02,469 (16913): Retrieved submission file 8430 for 'test_compile' action: /tmp/2015-11-14T20:49:02.469806
2015-11-14 20:49:02,471 (16913): Valid ZIP file
2015-11-14 20:49:02,471 (16913): Extracting ZIP file.
Traceback (most recent call last):
  File "/usr/local/bin/opensubmit-exec", line 9, in <module>
    load_entry_point('opensubmit-exec==0.5.2', 'console_scripts', 'opensubmit-exec')()
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/executor/cmdline.py", line 90, in console_script
    run(EXECUTOR_CONFIG_FILE)
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/executor/__init__.py", line 416, in run
    finalpath=_unpack_job(config, fname, submid, action)
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/executor/__init__.py", line 235, in _unpack_job
    f.extractall(finalpath)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1082, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python2.7/zipfile.py", line 1010, in open
    close_fileobj=should_close)
  File "/usr/lib/python2.7/zipfile.py", line 530, in __init__
    raise NotImplementedError("compression type %d (%s)" % (self._compress_type, descr))
NotImplementedError: compression type 14 (lzma)

**Comment by thehappyhippo** [comment]
There are other issues except decompression, encode and decode can result in exceptions
https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L75,https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L83, https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L295,https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L299,https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L389,
easy fix with errors='ignore' and all I/O including decompression are also points for exceptions. I had some of then in the windows port with strange timing issues. Could not delete closed file https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L158 because of used by other process. And
https://github.com/troeger/opensubmit/blob/master/executor/opensubmit/executor/__init__.py#L146
could not overwrite the file if already exists on Windows. Most I/O timing issues could be resolved with python 'with block'. I will make a pull maybe latter this week.

**Comment by Feinbube** [comment]
Is this fixed? If not, please add it to a milestone!

**Comment by troeger** [comment]
We restrict this issue to the  "NotImplementedError: compression type 14 (lama)" problem from here on. With respect to this, it is not fixed so far.

**Comment by troeger** [comment]
Seems like the patch already included the neccessary safeguards around the decompression code.
