### ISSUE TITLE
Django 1.9rc1 breaks opensubmit-web 0.5.7 

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#88]
We did the upgrade but there seams an error in the updated Django package. Error after upgrade is 
 AppRegistryNotReady: Apps aren't loaded yet.
Solution downgrade django to 1.8.6 and install 0.5.6 again.

Log:
pip install --upgrade https://github.com/troeger/opensubmit/releases/download/0.5.7/opensubmit-web-0.5.7.tar.gz
Downloading/unpacking https://github.com/troeger/opensubmit/releases/download/0.5.7/opensubmit-web-0.5.7.tar.gz
  Downloading opensubmit-web-0.5.7.tar.gz (619Kb): 619Kb downloaded
  Running setup.py egg_info for package from https://github.com/troeger/opensubmit/releases/download/0.5.7/opensubmit-web-0.5.7.tar.gz

Downloading/unpacking Django>=1.8 from https://pypi.python.org/packages/source/D/Django/Django-1.9rc1.tar.gz#md5=b971686521ea09b4bf82aec3e794fcbc (from opensubmit-web==0.5.7)
  Downloading Django-1.9rc1.tar.gz (7.3Mb): 7.3Mb downloaded
  Running setup.py egg_info for package Django

    no previously-included directories found matching 'django/contrib/admin/bin'
    warning: no previously-included files matching '__pycache__' found under directory '*'
Requirement already up-to-date: django-bootstrap-form in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: djangorestframework>=2.4 in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: django-grappelli in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: requests>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: pycrypto in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: pyjwkest in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: python-social-auth in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: python-openid in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: python-oauth2 in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from opensubmit-web==0.5.7)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pyjwkest->opensubmit-web==0.5.7)
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from pyjwkest->opensubmit-web==0.5.7)
Requirement already up-to-date: requests-oauthlib>=0.3.1 in /usr/local/lib/python2.7/dist-packages (from python-social-auth->opensubmit-web==0.5.7)
Requirement already up-to-date: PyJWT>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from python-social-auth->opensubmit-web==0.5.7)
Installing collected packages: Django, opensubmit-web
  Found existing installation: Django 1.8.6
    Uninstalling Django:
      Successfully uninstalled Django
  Running setup.py install for Django

    no previously-included directories found matching 'django/contrib/admin/bin'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    changing mode of build/scripts-2.7/django-admin.py from 644 to 755
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/django/conf/app_template/apps.py', 4, 7, 'class {{ camel_case_app_name }}Config(AppConfig):\n'))

    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/django/conf/app_template/models.py', 1, 26, '{{ unicode_literals }}from django.db import models\n'))

    changing mode of /usr/local/bin/django-admin.py to 755
    Installing django-admin script to /usr/local/bin
  Found existing installation: opensubmit-web 0.5.6
    Uninstalling opensubmit-web:
      Successfully uninstalled opensubmit-web
  Running setup.py install for opensubmit-web

    Installing opensubmit-web script to /usr/local/bin
Successfully installed Django opensubmit-web
Cleaning up...

opensubmit-web configure
Looking for config files ...
Config file found at /etc/opensubmit/settings.ini
Checking configuration of the OpenSubmit web application...
Using /etc/opensubmit/settings.ini
Traceback (most recent call last):
  File "/usr/local/bin/opensubmit-web", line 9, in <module>
    load_entry_point('opensubmit-web==0.5.7', 'console_scripts', 'opensubmit-web')()
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/cmdline.py", line 179, in console_script
    if not check_web_config_consistency(config):
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/cmdline.py", line 99, in check_web_config_consistency
    django_admin(["check"])
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/cmdline.py", line 17, in django_admin
    execute_from_command_line([sys.argv[0]]+args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/app.py", line 2, in <module>
    from signalhandlers import *
  File "/usr/local/lib/python2.7/dist-packages/opensubmit/signalhandlers.py", line 3, in <module>
    from django.contrib.auth.models import User, Group, Permission
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by thehappyhippo** [comment]
downgrade django to 1.8.6 after opensubmit-web 0.5.7 upgrade restores a working environment
